#################################### common config : ####################################
# 应用服务web访问端口
server:
  port: 8087

spring:
  application:
    name: sca-order
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848 # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/scadb
    username: root
    password: root